Add HDM to oss compose
voxpupuli/crafty pull request #39
Opened 2024-02-21 13:13 UTC by tuxmea

issue: we need to have at least one agent connected to puppetserver with entries in puppetdb.

going to copy the parts from ha

2024-02-21 16:33 UTC, rwaffen requested changes
please also add to the readme how to use this. maybe we should add a dedicated readme like in the ha example 🤔

2024-02-21 16:33 UTC, rwaffen commented on puppet/oss/.env
> +HDM_REGISTRY_PATH = "ghcr.io/betadots"
please don't use this pattern, i want to remove it. when doing this, renovate cannot scan for new images

2024-02-21 16:33 UTC, rwaffen commented on puppet/oss/compose.yaml
> +      - 8080:8080
you don't need to expose the port, if you don't want to use it from the outside of this stack. the container to each other can see the open ports without an explicit expose.

2024-02-21 16:33 UTC, rwaffen commented on puppet/oss/compose.yaml
> +    image: ${HDM_REGISTRY_PATH}/hdm:latest
please do full path hier, like mentioned above.

2024-02-21 16:33 UTC, rwaffen commented on puppet/oss/compose.yaml
> +      - ./agent-ssl:/etc/puppetlabs/puppet/ssl
please add the agent-ssl to gitignore, like in the ha sample

2024-02-21 16:33 UTC, rwaffen commented on puppet/oss/compose.yaml
> +      - ./puppet.conf:/etc/puppetlabs/puppet/puppet.conf:ro
where is the puppet.conf coming from? it is not in this pr?

2024-04-05 12:42 UTC, rwaffen approved these changes

2024-04-05 12:46 UTC, tuxmea commented
Looks good to me. As I am the author of this PR, I am not able to approve.

2024-04-05 12:51 UTC, merged