Add documentation on how to update a tagged container
voxpupuli/crafty pull request #4
Opened 2023-10-19 11:58 UTC by rwaffen

2023-10-19 12:06 UTC, bastelfreak requested changes

2023-10-19 12:06 UTC, bastelfreak commented on docs/how-to-build.md
> +git tag -d 7.13.0
I don't think we should modify tags. This will create conflicts for people that have the old tag locally.

2023-10-19 12:19 UTC, rwaffen commented on docs/how-to-build.md
> +git tag -d 7.13.0
we shouldn't do this, yes, but if we have to, i wanted to have documented how you have to do it.

2023-10-19 12:20 UTC, rwaffen commented on docs/how-to-build.md
> +git tag -d 7.13.0
maybe we should use a version file, and get the version from there 🤔 ... we rely somewhat to much on the tag name here

2023-10-20 06:03 UTC, tuxmea commented on docs/how-to-build.md
> +git tag -d 7.13.0
I prefer to use the tags to identify Puppet version to put inside containers.
I don't like the idea to re-use existing tags and point them to new commits.

How about the following idea:

- tag 7.13.1 builds with the latest available version 7.13.1 from puppet.
- If puppet release is at 7.13.1-1 this version is used at initial build time.

If you want to update the container, after puppet has released 7.13.1-2 one can start from tag 7.13.1 (`git checkout 7.13.1`) do the required adoptions and push a new tag (`git tag 7.13.1-2`)

2023-10-20 08:06 UTC, bastelfreak commented on docs/how-to-build.md
> +git tag -d 7.13.0
I agree with @tuxmea here. I think we should never manipulate the history and instead use a pkgrel style and append -1, then -2 etc.

2023-11-09 08:19 UTC, rwaffen commented on docs/how-to-build.md
> +git tag -d 7.13.0
lets discuss this in #5

2023-11-09 08:19 UTC, closed without merging